---
output:
  html_document:
    css: "assets/leaflet_style.css"
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)

# Tidyverse
library(tidyverse)

# Mapping
library(leaflet)
library(sf)
library(geojsonio)
library(htmltools)
library(mapview)
library(DT)

# SOE + popups
library(envreportutils)

# Load data
grizzdata_full <- read_rds(here("data/grizzdata_full.rds"))
grizzdata_full <- st_transform(grizzdata_full, crs = 4326) # convert to lat/long
```

``` {r popups and labels, include=FALSE, warning=FALSE}

# Popup for conservation status tab
popup_text1 <- dplyr::select(grizzdata_full, gbpu_name, threat_class, adults, 
                             calcrank, popiso, trend) %>% # Summary data for text popups
  rename("Population Name" = gbpu_name,
         "Overall Threat Score" = threat_class,
         "M-Rank" = calcrank,
         #"Overall Status" = status,
         "Population Size" = adults,
         "Isolation" = popiso,
         "Trend" = trend) 
st_geometry(popup_text1) <- NULL # as df

constatus_popup <- leafpop::popupTable(popup_text1,
                                   row.numbers = F, 
                                   feature.id = F)
# Habitat classification popup
raster_popups <- read_rds(here("out/raster_popups.rds"))

# Popup for population tab
popup_text2 <- dplyr::select(grizzdata_full, gbpu_name, adults, 
                               pop_density, area_sq_km) %>% # Summary data for text popups
  rename("Population Name" = gbpu_name,
         "Population Size (Adults)" = adults,
         "Population Density (Adults/1000^2s)" = pop_density,
         "Habitat Area (Sq. Km.)" = area_sq_km) 
st_geometry(popup_text2) <- NULL # as df

population_popup <- leafpop::popupTable(popup_text2,
                                   row.numbers = F, 
                                   feature.id = F)

popup_options <-  popupOptions(autoPan = TRUE,
                               keepInView = TRUE,
                               closeOnClick = TRUE,
                               autoPanPaddingTopLeft = c(120, 10),
                               autoPanPaddingBottomRight = c(120,10))
# Label 1
labs <- dplyr::select(grizzdata_full, gbpu_name, pop_density, calcrank, threat_class)
st_geometry(labs) <- NULL # as df

lab1 <- lapply(seq(nrow(labs)), function(i) {
  paste0( '<b>', labs[i, "gbpu_name"], ', ',  
          labs[i, "calcrank"], '</b>') 
})

lab2 <- lapply(seq(nrow(labs)), function(i) {
  paste0( '<b>', labs[i, "gbpu_name"], ', ',  
          labs[i, "pop_density"], '</b>') 
})

lab3 <- lapply(seq(nrow(labs)), function(i) {
  paste0( '<b>', labs[i, "gbpu_name"], ', ',  
          labs[i, "threat_class"], '</b>') 
})

# Prep - colour palettes
palette1 <- colorFactor(palette = 'viridis', grizzdata_full$calcsrank, reverse = TRUE)
palette2 <- colorNumeric(palette = 'viridis', grizzdata_full$pop_density, reverse = TRUE)
palette3 <- colorFactor(palette = 'viridis', grizzdata_full$threat_class, reverse = TRUE)

```

# {.tabset .tabset-fade}

```{r grizz_map, warning=FALSE, echo=FALSE}
grizzmap <- leaflet(width = "900px", height = "500px") %>%  # generate leaflet map
  addProviderTiles(providers$Stamen.Terrain, group = "Terrain") %>%
  add_bc_home_button() %>%
  set_bc_view()

```

## Conservation Status

```{r, warning=FALSE, echo=FALSE}
grizzmap %>% 
  addPolygons(data = grizzdata_full, #group = "Conservation Status",
              stroke = T, weight = 1, color = "black", # Add border to polygons
              fillOpacity = 0.5, # Polygon fill
              fillColor = ~palette1(grizzdata_full$calcsrank),
              label = lapply(lab1, htmltools::HTML),
              labelOptions = labelOptions(direction = "auto", textsize = "12px"),
              popup = constatus_popup,
              popupOptions = popup_options,
              highlight = highlightOptions( # Highlight interaction for mouse hover
                weight = 3,
                color = "yellow",
                bringToFront = T)) %>%
  addLegend("bottomright", pal = palette1, values = grizzdata_full$calcsrank,
            title = "Conservation Status", na.label = "Extirpated",
            opacity = 1) #%>%
  #addLayersControl(overlayGroups = c("Terrain", "Topography"))
```

## Population Density Estimate

``` {r, warning=FALSE, echo=FALSE}
grizzmap %>%
  addPolygons(data = grizzdata_full, #group = "Population Estimate",
              stroke = T, weight = 1, color = "black",
              fillOpacity = 0.5,
              fillColor = ~palette2(grizzdata_full$pop_density),
              label = lapply(lab2, htmltools::HTML),
              labelOptions = labelOptions(direction = "auto", textsize = "12px"),
              popup = population_popup,
              popupOptions = popup_options,
              highlight = highlightOptions( # Highlight interaction for mouse hover
              weight = 3,
              color = "yellow",
              bringToFront = T)) %>%
  addLegend("bottomright", pal = palette2, values = grizzdata_full$pop_density,
            title = "Population Density", na.label = "Extirpated",
            opacity = 1) #%>%
  # addLayersControl(overlayGroups = c("Terrain", "Topography"))
```

## Threat Classification

``` {r, warning=FALSE, echo=FALSE}
grizzmap %>% 
  addPolygons(data = grizzdata_full,
              stroke = T, weight = 1, color = "black", # Add border to polygons
              fillOpacity = 0.5, # Polygon fill
              fillColor = ~palette3(grizzdata_full$transportationcalc),
              popup = raster_popups,
              popupOptions = popup_options,
              group = "Transportation",
              label = lapply(lab3, htmltools::HTML),
              labelOptions = labelOptions(direction = "auto", textsize = "12px"),
              highlight = highlightOptions( # Highlight interaction for mouse hover
                weight = 3,
                color = "yellow",
                bringToFront = T)) %>%
  addPolygons(data = grizzdata_full,
              stroke = T, weight = 1, color = "black",
              fillOpacity = 0.5,
              fillColor = ~palette3(grizzdata_full$energycalc),
              popup = raster_popups,
              popupOptions = popup_options,
              group = "Energy",
              label = lapply(lab3, htmltools::HTML),
              labelOptions = labelOptions(direction = "auto", textsize = "12px"),
              highlight = highlightOptions(
                weight = 3,
                color = "yellow",
                bringToFront = T)) %>%
  addPolygons(data = grizzdata_full,
              stroke = T, weight = 1, color = "black",
              fillOpacity = 0.5,
              fillColor = ~palette3(grizzdata_full$humanintrusioncalc),
              popup = raster_popups,
              popupOptions = popup_options,
              group = "Human Intrusion",
              label = lapply(lab3, htmltools::HTML),
              labelOptions = labelOptions(direction = "auto", textsize = "12px"),
              highlight = highlightOptions(
                weight = 3,
                color = "yellow",
                bringToFront = T)) %>%
  addPolygons(data = grizzdata_full,
              stroke = T, weight = 1, color = "black",
              fillOpacity = 0.5,
              fillColor = ~palette3(grizzdata_full$residentialcalc),
              popup = raster_popups,
              popupOptions = popup_options,
              group = "Residential",
              label = lapply(lab3, htmltools::HTML),
              labelOptions = labelOptions(direction = "auto", textsize = "12px"),
              highlight = highlightOptions(
                weight = 3,
                color = "yellow",
                bringToFront = T)) %>%
  addPolygons(data = grizzdata_full,
              stroke = T, weight = 1, color = "black",
              fillOpacity = 0.5,
              fillColor = ~palette3(grizzdata_full$agriculturecalc),
              popup = raster_popups,
              popupOptions = popup_options,
              group = "Agriculture",
              label = lapply(lab3, htmltools::HTML),
              labelOptions = labelOptions(direction = "auto", textsize = "12px"),
              highlight = highlightOptions(
                weight = 3,
                color = "yellow",
                bringToFront = T)) %>%
  addPolygons(data = grizzdata_full,
              stroke = T, weight = 1, color = "black",
              fillOpacity = 0.5,
              fillColor = ~palette3(grizzdata_full$biousecalc),
              popup = raster_popups,
              popupOptions = popup_options,
              group = "Biouse",
              label = lapply(lab3, htmltools::HTML),
              labelOptions = labelOptions(direction = "auto", textsize = "12px"),
              highlight = highlightOptions(
                weight = 3,
                color = "yellow",
                bringToFront = T)) %>%
  addPolygons(data = grizzdata_full,
              stroke = T, weight = 1, color = "black",
              fillOpacity = 0.5,
              fillColor = ~palette3(grizzdata_full$climatechangecalc),
              popup = raster_popups,
              popupOptions = popup_options,
              group = "Climate Change",
              label = lapply(lab3, htmltools::HTML),
              labelOptions = labelOptions(direction = "auto", textsize = "12px"),
              highlight = highlightOptions(
                weight = 3,
                color = "yellow",
                bringToFront = T)) %>%
  addLayersControl(
    baseGroups = c("Transportation", "Energy", "Human Intrusion", "Residential",
                   "Agriculture", "Biouse", "Climate Change"),
    #overlayGroups = c("Terrain", "OSM (Default)"),
    options = layersControlOptions(collapsed = FALSE)) %>%
  addLegend("bottomright", pal = palette3, values = grizzdata_full$threat_class,
            title = "Threat Rank", na.label = "Extirpated",
            opacity = 1)
#%>%
  #addLayersControl(overlayGroups = c("Terrain", "Topography"))
```
